/*
-- Query: SELECT * FROM pokedex.ability
LIMIT 0, 1000

-- Date: 2017-06-18 04:06
*/
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (1,'stench','Has a 10% chance of making target Pokémon flinch with each hit.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (2,'drizzle','Summons rain that lasts indefinitely upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (3,'speed-boost','Raises Speed one stage after each turn.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (4,'battle-armor','Protects against critical hits.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (5,'sturdy','Prevents being KOed from full HP, leaving 1 HP instead.  Protects against the one-hit KO moves regardless of HP.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (6,'damp','Prevents self destruct, explosion, and aftermath from working while the Pokémon is in battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (7,'limber','Prevents paralysis.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (8,'sand-veil','Increases evasion to 1.25× during a sandstorm.  Protects against sandstorm damage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (9,'static','Has a 30% chance of paralyzing attacking Pokémon on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (10,'volt-absorb','Absorbs electric moves, healing for 1/4 max HP.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (11,'water-absorb','Absorbs water moves, healing for 1/4 max HP.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (12,'oblivious','Prevents infatuation and protects against captivate.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (13,'cloud-nine','Negates all effects of weather, but does not prevent the weather itself.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (14,'compound-eyes','Increases moves\' accuracy to 1.3×.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (15,'insomnia','Prevents sleep.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (16,'color-change','Changes type to match when hit by a damaging move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (17,'immunity','Prevents poison.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (18,'flash-fire','Protects against fire moves.  Once one has been blocked, the Pokémon\'s own Fire moves inflict 1.5× damage until it leaves battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (19,'shield-dust','Protects against incoming moves\' extra effects.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (20,'own-tempo','Prevents confusion.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (21,'suction-cups','Prevents being forced out of battle by other Pokémon\'s moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (22,'intimidate','Lowers opponents\' Attack one stage upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (23,'shadow-tag','Prevents opponents from fleeing or switching out.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (24,'rough-skin','Damages attacking Pokémon for 1/8 their max HP on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (25,'wonder-guard','Protects against damaging moves that are not super effective.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (26,'levitate','Evades ground moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (27,'effect-spore','Has a 30% chance of inflcting either paralysis, poison, or sleep on attacking Pokémon on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (28,'synchronize','Copies burns, paralysis, and poison received onto the Pokémon that inflicted them.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (29,'clear-body','Prevents stats from being lowered by other Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (30,'natural-cure','Cures any major status ailment upon switching out.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (31,'lightning-rod','Redirects single-target electric moves to this Pokémon where possible.  Absorbs Electric moves, raising Special Attack one stage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (32,'serene-grace','Doubles the chance of moves\' extra effects occurring.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (33,'swift-swim','Doubles Speed during rain.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (34,'chlorophyll','Doubles Speed during strong sunlight.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (35,'illuminate','Doubles the wild encounter rate.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (36,'trace','Copies an opponent\'s ability upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (37,'huge-power','Doubles Attack in battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (38,'poison-point','Has a 30% chance of poisoning attacking Pokémon on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (39,'inner-focus','Prevents flinching.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (40,'magma-armor','Prevents freezing.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (41,'water-veil','Prevents burns.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (42,'magnet-pull','Prevents steel opponents from fleeing or switching out.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (43,'soundproof','Protects against sound-based moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (44,'rain-dish','Heals for 1/16 max HP after each turn during rain.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (45,'sand-stream','Summons a sandstorm that lasts indefinitely upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (46,'pressure','Increases the PP cost of moves targetting the Pokémon by one.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (47,'thick-fat','Halves damage from fire and ice moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (48,'early-bird','Makes sleep pass twice as quickly.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (49,'flame-body','Has a 30% chance of burning attacking Pokémon on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (50,'run-away','Ensures success fleeing from wild battles.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (51,'keen-eye','Prevents accuracy from being lowered.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (52,'hyper-cutter','Prevents Attack from being lowered by other Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (53,'pickup','Picks up other Pokémon\'s used and Flung held items.  May also pick up an item after battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (54,'truant','Skips every second turn.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (55,'hustle','Strengthens physical moves to inflict 1.5× damage, but decreases their accuracy to 0.8×.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (56,'cute-charm','Has a 30% chance of infatuating attacking Pokémon on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (57,'plus','Increases Special Attack to 1.5× when a friendly Pokémon has plus or minus.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (58,'minus','Increases Special Attack to 1.5× when a friendly Pokémon has plus or minus.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (59,'forecast','Changes castform\'s type and form to match the weather.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (60,'sticky-hold','Prevents a held item from being removed by other Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (61,'shed-skin','Has a 33% chance of curing any major status ailment after each turn.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (62,'guts','Increases Attack to 1.5× with a major status ailment.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (63,'marvel-scale','Increases Defense to 1.5× with a major status ailment.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (64,'liquid-ooze','Damages opponents using leeching moves for as much as they would heal.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (65,'overgrow','Strengthens grass moves to inflict 1.5× damage at 1/3 max HP or less.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (66,'blaze','Strengthens fire moves to inflict 1.5× damage at 1/3 max HP or less.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (67,'torrent','Strengthens water moves to inflict 1.5× damage at 1/3 max HP or less.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (68,'swarm','Strengthens bug moves to inflict 1.5× damage at 1/3 max HP or less.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (69,'rock-head','Protects against recoil damage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (70,'drought','Summons strong sunlight that lasts indefinitely upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (71,'arena-trap','Prevents opponents from fleeing or switching out.  Eluded by flying-types and Pokémon in the air.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (72,'vital-spirit','Prevents sleep.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (73,'white-smoke','Prevents stats from being lowered by other Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (74,'pure-power','Doubles Attack in battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (75,'shell-armor','Protects against critical hits.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (76,'air-lock','Negates all effects of weather, but does not prevent the weather itself.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (77,'tangled-feet','Doubles evasion when confused.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (78,'motor-drive','Absorbs electric moves, raising Speed one stage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (79,'rivalry','Increases damage inflicted to 1.25× against Pokémon of the same gender, but decreases damage to 0.75× against the opposite gender.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (80,'steadfast','Raises Speed one stage upon flinching.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (81,'snow-cloak','Increases evasion to 1.25× during hail.  Protects against hail damage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (82,'gluttony','Makes the Pokémon eat any held Berry triggered by low HP below 1/2 its max HP.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (83,'anger-point','Raises Attack to the maximum of six stages upon receiving a critical hit.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (84,'unburden','Doubles Speed upon using or losing a held item.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (85,'heatproof','Halves damage from fire moves and burns.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (86,'simple','Doubles the Pokémon\'s stat modifiers.  These doubled modifiers are still capped at -6 or 6 stages.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (87,'dry-skin','Causes 1/8 max HP in damage each turn during strong sunlight, but heals for 1/8 max HP during rain.  Increases damage from fire moves to 1.25×, but absorbs water moves, healing for 1/4 max HP.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (88,'download','Raises the attack stat corresponding to the opponents\' weaker defense one stage upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (89,'iron-fist','Strengthens punch-based moves to 1.2× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (90,'poison-heal','Heals for 1/8 max HP after each turn when poisoned in place of damage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (91,'adaptability','Increases the same-type attack bonus from 1.5× to 2×.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (92,'skill-link','Extends two-to-five-hit moves and triple kick to their full length every time.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (93,'hydration','Cures any major status ailment after each turn during rain.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (94,'solar-power','Increases Special Attack to 1.5× but costs 1/8 max HP after each turn during strong sunlight.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (95,'quick-feet','Increases Speed to 1.5× with a major status ailment.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (96,'normalize','Makes the Pokémon\'s moves all act normal-type.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (97,'sniper','Strengthens critical hits to inflict 3× damage rather than 2×.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (98,'magic-guard','Protects against damage not directly caused by a move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (99,'no-guard','Ensures all moves used by and against the Pokémon hit.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (100,'stall','Makes the Pokémon move last within its move\'s priority bracket.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (101,'technician','Strengthens moves of 60 base power or less to 1.5× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (102,'leaf-guard','Protects against major status ailments during strong sunlight.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (103,'klutz','Prevents the Pokémon from using its held item in battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (104,'mold-breaker','Bypasses targets\' abilities if they could hinder or prevent a move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (105,'super-luck','Raises moves\' critical hit rates one stage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (106,'aftermath','Damages the attacker for 1/4 its max HP when knocked out by a contact move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (107,'anticipation','Notifies all trainers upon entering battle if an opponent has a super-effective move, self destruct, explosion, or a one-hit KO move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (108,'forewarn','Reveals the opponents\' strongest move upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (109,'unaware','Ignores other Pokémon\'s stat modifiers for damage and accuracy calculation.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (110,'tinted-lens','Doubles damage inflicted with not-very-effective moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (111,'filter','Decreases damage taken from super-effective moves by 1/4.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (112,'slow-start','Halves Attack and Speed for five turns upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (113,'scrappy','Lets the Pokémon\'s normal and fighting moves hit ghost Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (114,'storm-drain','Redirects single-target water moves to this Pokémon where possible.  Absorbs Water moves, raising Special Attack one stage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (115,'ice-body','Heals for 1/16 max HP after each turn during hail.  Protects against hail damage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (116,'solid-rock','Decreases damage taken from super-effective moves by 1/4.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (117,'snow-warning','Summons hail that lasts indefinitely upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (118,'honey-gather','The Pokémon may pick up honey after battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (119,'frisk','Reveals an opponent\'s held item upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (120,'reckless','Strengthens recoil moves to 1.2× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (121,'multitype','Changes arceus\'s type and form to match its held Plate.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (122,'flower-gift','Increases friendly Pokémon\'s Attack and Special Defense to 1.5× during strong sunlight.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (123,'bad-dreams','Damages sleeping opponents for 1/8 their max HP after each turn.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (124,'pickpocket','Steals attacking Pokémon\'s held items on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (125,'sheer-force','Strengthens moves with extra effects to 1.3× their power, but prevents their extra effects.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (126,'contrary','Inverts stat changes.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (127,'unnerve','Prevents opposing Pokémon from eating held Berries.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (128,'defiant','Raises Attack two stages upon having any stat lowered.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (129,'defeatist','Halves Attack and Special Attack at 50% max HP or less.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (130,'cursed-body','Has a 30% chance of Disabling any move that hits the Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (131,'healer','Has a 30% chance of curing each adjacent ally of any major status ailment after each turn.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (132,'friend-guard','Decreases all direct damage taken by friendly Pokémon to 0.75×.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (133,'weak-armor','Raises Speed and lowers Defense by one stage each upon being hit by a physical move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (134,'heavy-metal','Doubles the Pokémon\'s weight.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (135,'light-metal','Halves the Pokémon\'s weight.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (136,'multiscale','Halves damage taken from full HP.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (137,'toxic-boost','Increases Attack to 1.5× when poisoned.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (138,'flare-boost','Increases Special Attack to 1.5× when burned.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (139,'harvest','Has a 50% chance of restoring a used Berry after each turn if the Pokémon has held no items in the meantime.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (140,'telepathy','Protects against friendly Pokémon\'s damaging moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (141,'moody','Raises a random stat two stages and lowers another one stage after each turn.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (142,'overcoat','Protects against damage from weather.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (143,'poison-touch','Has a 30% chance of poisoning target Pokémon upon contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (144,'regenerator','Heals for 1/3 max HP upon switching out.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (145,'big-pecks','Protects against Defense drops.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (146,'sand-rush','Doubles Speed during a sandstorm.  Protects against sandstorm damage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (147,'wonder-skin','Lowers incoming non-damaging moves\' base accuracy to exactly 50%.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (148,'analytic','Strengthens moves to 1.3× their power when moving last.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (149,'illusion','Takes the appearance of the last conscious party Pokémon upon being sent out until hit by a damaging move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (150,'imposter','Transforms upon entering battle.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (151,'infiltrator','Bypasses light screen, reflect, and safeguard.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (152,'mummy','Changes attacking Pokémon\'s abilities to Mummy on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (153,'moxie','Raises Attack one stage upon KOing a Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (154,'justified','Raises Attack one stage upon taking damage from a dark move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (155,'rattled','Raises Speed one stage upon being hit by a dark, ghost, or bug move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (156,'magic-bounce','Reflects most non-damaging moves back at their user.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (157,'sap-sipper','Absorbs grass moves, raising Attack one stage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (158,'prankster','Raises non-damaging moves\' priority by one stage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (159,'sand-force','Strengthens rock, ground, and steel moves to 1.3× their power during a sandstorm.  Protects against sandstorm damage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (160,'iron-barbs','Damages attacking Pokémon for 1/8 their max HP on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (161,'zen-mode','Changes darmanitan\'s form after each turn depending on its HP: Zen Mode below 50% max HP, and Standard Mode otherwise.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (162,'victory-star','Increases moves\' accuracy to 1.1× for friendly Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (163,'turboblaze','Bypasses targets\' abilities if they could hinder or prevent moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (164,'teravolt','Bypasses targets\' abilities if they could hinder or prevent moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (165,'aroma-veil','Protects allies against moves that affect their mental state.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (166,'flower-veil','Protects friendly grass Pokémon from having their stats lowered by other Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (167,'cheek-pouch','Restores HP upon eating a Berry, in addition to the Berry\'s effect.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (168,'protean','Changes the bearer\'s type to match each move it uses.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (169,'fur-coat','Halves damage from physical attacks.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (170,'magician','Steals the target\'s held item when the bearer uses a damaging move.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (171,'bulletproof','Protects against bullet, ball, and bomb-based moves.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (172,'competitive','Raises Special Attack by two stages upon having any stat lowered.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (173,'strong-jaw','Strengthens biting moves to 1.5× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (174,'refrigerate','Turns the bearer\'s normal moves into ice moves and strengthens them to 1.3× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (175,'sweet-veil','Prevents friendly Pokémon from sleeping.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (176,'stance-change','Changes aegislash to Blade Forme before using a damaging move, or Shield Forme before using kings shield.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (177,'gale-wings','Raises flying moves\' priority by one stage.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (178,'mega-launcher','Strengthens aura and pulse moves to 1.5× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (179,'grass-pelt','Boosts Defense while grassy terrain is in effect.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (180,'symbiosis','Passes the bearer\'s held item to an ally when the ally uses up its item.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (181,'tough-claws','Strengthens moves that make contact to 1.33× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (182,'pixilate','Turns the bearer\'s normal moves into fairy moves and strengthens them to 1.3× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (183,'gooey','Lowers attacking Pokémon\'s Speed by one stage on contact.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (184,'aerilate','Turns the bearer\'s normal moves into flying moves and strengthens them to 1.3× their power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (185,'parental-bond','Lets the bearer hit twice with damaging moves.  The second hit has half power.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (186,'dark-aura','Strengthens dark moves to 1.33× their power for all friendly and opposing Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (187,'fairy-aura','Strengthens fairy moves to 1.33× their power for all friendly and opposing Pokémon.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (188,'aura-break','Makes dark aura and fairy aura weaken moves of their respective types.');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (189,'primordial-sea','');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (190,'desolate-land','');
INSERT INTO `ability` (`id`,`name`,`description`) VALUES (191,'delta-stream','');
